services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: bit-ocean-verdaccio
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
    env:
      VERDACCIO_PUBLIC_URL: 'https://npm/bit-ocean.studio'
volumes:
  verdaccio:
    driver: local
