services:
  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    container_name: bit-ocean-verdaccio
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
volumes:
  verdaccio:
    driver: local
